# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('snapshot_number', models.IntegerField()),
                ('snapshot_time', models.DateTimeField()),
            ],
        ),
    ]
