# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('article', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
