# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_courtorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalDoc',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('article', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='article',
            field=markdownx.models.MarkdownxField(help_text='Markdown please'),
        ),
    ]
