# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20170312_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtorder',
            name='location',
        ),
        migrations.DeleteModel(
            name='CourtOrder',
        ),
    ]
