# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20170312_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FederalDoc',
        ),
    ]
